name: Auto merge on push
on: 
  push:
    branches:
      - 'map'
      - 'be-start'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge staging -> uat
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
