name: Auto merge on push
run-name: ${{ github.actor }} pushed his branch
on: 
  push:
    branches:
      - 'map'
      - 'be-start'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge staging -> uat
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
